server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8085


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  profiles:
    active: dev
management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
   web:
     exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
   instances:
    ratingHotelBreaker:
    registrationHealthIndicator: true
    eventConsumerBufferSize: 10
    failureRateThreshold: 50
    minimumNumberOfCalls: 5
    automaticTransitionFromOpenToHalfOpenEnabled: true
    waitDurationInOpenState: 6s
    permittedNumberOfCallsInHalfOpenState: 3
    slidingWindowSize: 10
    slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
      max-attempts: 3
      wait-duration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s





